https://archive.ics.uci.edu/ml/datasets/Auto+MPG

Using the information, predict the origin of the vehicle, either North America, Europe, or Asia. 

In [35]:
import pandas as pd
import numpy as np

In [28]:
cars = pd.read_csv("auto.csv")

In [29]:
cars

mpg  cylinders  displacement horsepower  weight  acceleration  year  \
0     18          8           307        130    3504          12.0    70   
1     15          8           350        165    3693          11.5    70   
2     18          8           318        150    3436          11.0    70   
3     16          8           304        150    3433          12.0    70   
4     17          8           302        140    3449          10.5    70   
5     15          8           429        198    4341          10.0    70   
6     14          8           454        220    4354           9.0    70   
7     14          8           440        215    4312           8.5    70   
8     14          8           455        225    4425          10.0    70   
9     15          8           390        190    3850           8.5    70   
10    15          8           383        170    3563          10.0    70   
11    14          8           340        160    3609           8.0    70   
12    15          8           400        150    3761           9.5    70   
13    14          8           455        225    3086          10.0    70   
14    24          4           113         95    2372          15.0    70   
15    22          6           198         95    2833          15.5    70   
16    18          6           199         97    2774          15.5    70   
17    21          6           200         85    2587          16.0    70   
18    27          4            97         88    2130          14.5    70   
19    26          4            97         46    1835          20.5    70   
20    25          4           110         87    2672          17.5    70   
21    24          4           107         90    2430          14.5    70   
22    25          4           104         95    2375          17.5    70   
23    26          4           121        113    2234          12.5    70   
24    21          6           199         90    2648          15.0    70   
25    10          8           360        215    4615          14.0    70   
26    10          8           307        200    4376          15.0    70   
27    11          8           318        210    4382          13.5    70   
28     9          8           304        193    4732          18.5    70   
29    27          4            97         88    2130          14.5    71   
..   ...        ...           ...        ...     ...           ...   ...   
368   27          4           112         88    2640          18.6    82   
369   34          4           112         88    2395          18.0    82   
370   31          4           112         85    2575          16.2    82   
371   29          4           135         84    2525          16.0    82   
372   27          4           151         90    2735          18.0    82   
373   24          4           140         92    2865          16.4    82   
374   23          4           151          ?    3035          20.5    82   
375   36          4           105         74    1980          15.3    82   
376   37          4            91         68    2025          18.2    82   
377   31          4            91         68    1970          17.6    82   
378   38          4           105         63    2125          14.7    82   
379   36          4            98         70    2125          17.3    82   
380   36          4           120         88    2160          14.5    82   
381   36          4           107         75    2205          14.5    82   
382   34          4           108         70    2245          16.9    82   
383   38          4            91         67    1965          15.0    82   
384   32          4            91         67    1965          15.7    82   
385   38          4            91         67    1995          16.2    82   
386   25          6           181        110    2945          16.4    82   
387   38          6           262         85    3015          17.0    82   
388   26          4           156         92    2585 

In [30]:
list(cars.columns)

['mpg',
 'cylinders',
 'displacement',
 'horsepower',
 'weight',
 'acceleration',
 'year',
 'origin',
 'car_name']

In [37]:
unique_origions = cars["origin"].unique()
print unique_origions
unique_origions

[1 3 2]


array([1, 3, 2], dtype=int64)

In [32]:
cars["cylinders"].unique()

array([8, 4, 6, 3, 5], dtype=int64)

In [33]:
#Adding dummy variables to generate categorical values and dropping the original columns
dummy_cylinders = pd.get_dummies(cars["cylinders"], prefix="cyl")
cars = pd.concat([cars, dummy_cylinders], axis=1)
#print(cars.head())
dummy_years = pd.get_dummies(cars["year"], prefix="year")
cars = pd.concat([cars, dummy_years], axis=1)
cars = cars.drop("year", axis=1)
cars = cars.drop("cylinders", axis=1)
print(cars.head())

   mpg  displacement horsepower  weight  acceleration  origin  \
0   18           307        130    3504          12.0       1   
1   15           350        165    3693          11.5       1   
2   18           318        150    3436          11.0       1   
3   16           304        150    3433          12.0       1   
4   17           302        140    3449          10.5       1   

                    car_name  cyl_3  cyl_4  cyl_5   ...     year_73  year_74  \
0  chevrolet chevelle malibu      0      0      0   ...           0        0   
1          buick skylark 320      0      0      0   ...           0        0   
2         plymouth satellite      0      0      0   ...           0        0   
3              amc rebel sst      0      0      0   ...           0        0   
4                ford torino      0      0      0   ...           0        0   

   year_75  year_76  year_77  year_78  year_79  year_80  year_81  year_82  
0        0        0        0        0        0      

In [36]:
shuffled_rows = np.random.permutation(cars.index)
shuffled_cars = cars.iloc[shuffled_rows]

#Split into train and test sets
highest_train_row = int(cars.shape[0] * .70)
train = shuffled_cars.iloc[0:highest_train_row]
test = shuffled_cars.iloc[highest_train_row:]

In [38]:
from sklearn.linear_model import LogisticRegression

unique_origins = cars["origin"].unique()
unique_origins.sort()

#create a dictionary origin->relevant Logistic Reg model instance
models = {}

#For each value in unique_origins, train a logistic regression model with the following parameters:
#X: Dataframe containing just the cylinder & year binary columns.
#y: list (or Series) of Boolean values:
#True if observation's value for origin matches the current iterator variable.
#False if observation's value for origin doesn't match the current iterator variable.

features = [c for c in train.columns if c.startswith("cyl") or c.startswith("year")]

for origin in unique_origins:
    model = LogisticRegression()
    
    X_train = train[features]
    y_train = train["origin"] == origin

    model.fit(X_train, y_train)
    models[origin] = model

In [39]:
#For each origin value from unique_origins: Use the LogisticRegression predict_proba function to return the 3 lists of predicted
#probabilities for the test set and add to the testing_probs Dataframe.

testing_probs = pd.DataFrame(columns=unique_origins)
for origin in unique_origins:
    # Select testing features.
    X_test = test[features]   
    # Compute probability of observation being in the origin.
    testing_probs[origin] = models[origin].predict_proba(X_test)[:,1]

In [40]:
#To classify each observation we want to select the origin with the highest probability of classification for that observation.
#Classify each observation in the test set using the testing_probs Dataframe.

predicted_origins = testing_probs.idxmax(axis=1)
print(predicted_origins)


0      1
1      1
2      3
3      1
4      1
5      1
6      3
7      1
8      1
9      1
10     1
11     1
12     1
13     2
14     1
15     3
16     1
17     1
18     1
19     1
20     1
21     1
22     3
23     1
24     1
25     1
26     1
27     1
28     2
29     3
      ..
90     1
91     1
92     1
93     1
94     1
95     1
96     1
97     2
98     1
99     3
100    2
101    1
102    1
103    1
104    3
105    3
106    1
107    3
108    3
109    2
110    1
111    1
112    1
113    1
114    1
115    1
116    1
117    1
118    3
119    1
dtype: int64
